apiVersion: v1
kind: Namespace
metadata:
  name: getit-production
  labels:
    name: getit-production
    environment: production
    app.kubernetes.io/name: getit-commerce
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: terraform
    bangladesh.compliance/data-residency: "required"
    bangladesh.compliance/audit-logging: "enabled"
  annotations:
    description: "GetIt Multi-Vendor Ecommerce Platform - Production Environment"
    contact: "platform-team@getit.com.bd"
    cost-center: "production-ops"
    backup-policy: "daily"
    monitoring.prometheus.io/scrape: "true"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: getit-production-quota
  namespace: getit-production
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "50"
    services: "50"
    secrets: "100"
    configmaps: "100"
    count/deployments.apps: "50"
    count/replicasets.apps: "100"
    count/pods: "200"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: getit-production-limits
  namespace: getit-production
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
  - max:
      storage: "100Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim