apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-gateways-config
  namespace: production
  labels:
    app: payment-service
    config-type: bangladesh-payment
data:
  bkash-config.json: |
    {
      "baseUrl": "https://tokenized.pay.bka.sh/v1.2.0-beta",
      "sandboxUrl": "https://tokenized.sandbox.bka.sh/v1.2.0-beta",
      "timeout": 30000,
      "retryAttempts": 3,
      "supportedCurrencies": ["BDT"],
      "webhookEndpoint": "/webhooks/bkash",
      "features": {
        "createPayment": true,
        "executePayment": true,
        "queryPayment": true,
        "refundTransaction": true
      }
    }
  nagad-config.json: |
    {
      "baseUrl": "https://api.mynagad.com/api/dfs",
      "sandboxUrl": "https://sandbox.mynagad.com/api/dfs",
      "timeout": 30000,
      "retryAttempts": 3,
      "supportedCurrencies": ["BDT"],
      "webhookEndpoint": "/webhooks/nagad",
      "features": {
        "createPayment": true,
        "verifyPayment": true,
        "checkStatus": true,
        "refundTransaction": true
      }
    }
  rocket-config.json: |
    {
      "baseUrl": "https://api.rocket.com.bd/api/v1",
      "sandboxUrl": "https://sandbox.rocket.com.bd/api/v1",
      "timeout": 30000,
      "retryAttempts": 3,
      "supportedCurrencies": ["BDT"],
      "webhookEndpoint": "/webhooks/rocket",
      "features": {
        "cashIn": true,
        "cashOut": true,
        "sendMoney": true,
        "checkBalance": true
      }
    }
  payment-routing.json: |
    {
      "defaultGateway": "bkash",
      "failoverSequence": ["bkash", "nagad", "rocket"],
      "amountLimits": {
        "bkash": { "min": 10, "max": 25000 },
        "nagad": { "min": 10, "max": 25000 },
        "rocket": { "min": 10, "max": 15000 }
      },
      "feesStructure": {
        "bkash": { "percentage": 1.85, "fixed": 0 },
        "nagad": { "percentage": 1.99, "fixed": 0 },
        "rocket": { "percentage": 1.5, "fixed": 5 }
      }
    }