apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: production
  labels:
    app: api-gateway
    tier: core
    environment: production
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-loadbalancer
  namespace: production
  labels:
    app: api-gateway
    tier: core
    environment: production
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0